### ISSUE TITLE
can't make dirs in...

### ISSUE THREAD

**Issue by zccguagua** [Jay-huangjie/ACache#1]
突然出现
java.lang.RuntimeException: can't make dirs in /data/。。。/cache/ACache

**Comment by zccguagua** [comment]
解决了

**Comment by WuMingke** [comment]
> 解决了

请问怎么解决的呢

**Comment by zccguagua** [comment]
> > 解决了
> 
> 请问怎么解决的呢

太老了这个 现在项目中已经使用mmkv组件了
